### ISSUE TITLE
Add Ecmascript stage3 proposal support to acorn

### ISSUE THREAD

**Issue by tcitworld** [Polyconseil/easygettext#39]
Please add https://github.com/acornjs/acorn-stage3 support to acorn so that it doesn't fail on modern javascript. It could of course be configurable.

**Comment by gorkat** [comment]
First of all hello,

Could you give a bit more context about that?
Which kind of issue did you get?
Could you share a portion of code that could help us to reproduce it?

For the moment I didn't get any error parsing modern JavaScript so a bit of help to identify what's wrong will be appreciated :)

**Comment by tcitworld** [comment]
Hi and sorry for my previous short message.

I use the [dynamic-import proposal](https://github.com/tc39/proposal-dynamic-import) feature like this in the `<script>` portion of my Vue component:
```js
const Detector = () => import("./Detector.vue");
```
The parsing issue happens just before the `import`.
```
Trace: { SyntaxError: Unexpected token (58:23)
    at Parser.pp$4.raise ([...]/node_modules/acorn/dist/acorn.js:2756:13)
    at Parser.pp.unexpected ([...]/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp$3.parseExprAtom ([...]/node_modules/acorn/dist/acorn.js:2196:10)
    at Parser.pp$3.parseExprSubscripts ([...]/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary [...]/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps ([...]/node_modules/acorn/dist/acorn.js:1966:19)
    at Parser.pp$3.parseMaybeConditional ([...]/node_modules/acorn/dist/acorn.js:1949:19)
    at Parser.pp$3.parseMaybeAssign ([...]/node_modules/acorn/dist/acorn.js:1925:19)
    at Parser.pp$3.parseFunctionBody ([...]/node_modules/acorn/dist/acorn.js:2577:22)
    at Parser.pp$3.parseArrowExpression ([...]/node_modules/acorn/dist/acorn.js:2560:8)
    at Parser.pp$3.parseParenArrowList ([...]/node_modules/acorn/dist/acorn.js:2283:15)
    at Parser.pp$3.parseParenAndDistinguishExpression ([...]/node_modules/acorn/dist/acorn.js:2249:19)
    at Parser.pp$3.parseExprAtom ([...]/node_modules/acorn/dist/acorn.js:2163:41)
    at Parser.pp$3.parseExprSubscripts ([...]/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary ([...]/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps ([...]/node_modules/acorn/dist/acorn.js:1966:19)
  pos: 290,
  loc: Position { line: 58, column: 23 },
  raisedAt: 296 }
    at /[...]/node_modules/easygettext/src/extract-cli.js:71:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/[...]/node_modules/easygettext/src/extract-cli.js:57:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
Makefile:34 : la recette pour la cible « /tmp/template.pot » a échouée
make: *** [/tmp/template.pot] Erreur 1
```

**Comment by gorkat** [comment]
Ok I understand better now,
I'll have a look at it in the next days, thank you for the feedback !

**Comment by tcitworld** [comment]
I sent a PR. :)
