### ISSUE TITLE
Support es7 decorators

### ISSUE THREAD

**Issue by diego-vieira** [Polyconseil/easygettext#49]
Hi, acorn doesn't support ES7 decorators by default.

We're using [vue-class-component](https://github.com/vuejs/vue-class-component) and it's failing with `Unexpected character '@'`

Vue file
```vue
<template>
<div>
  Test1: <span v-translate>Test2</span>
</div>
</template>

<script>
import { Vue, Component } from "vue-property-decorator";
import Header from "@/header.vue";

@Component({
  components: {
    Header
  }
})

export default class App extends Vue {
  details = {}
}
</script>
```

Command
```
node_modules/.bin/gettext-extract --attribute v-translate --quiet --output /tmp/template.pot src/App.vue
[easygettext] extracting: 'src/App.vue
[easygettext] could not read: 'src/App.vue
Trace: { SyntaxError: Unexpected character '@' (10:0)
    at Parser.pp$4.raise (node_modules/acorn/dist/acorn.js:2756:13)
    at Parser.pp$8.getTokenFromCode (node_modules/acorn/dist/acorn.js:4905:8)
    at Parser.<anonymous> (node_modules/acorn-class-fields/inject.js:41:21)
    at Parser.getTokenFromCode (node_modules/acorn-private-methods/inject.js:30:21)
    at Parser.pp$8.readToken (node_modules/acorn/dist/acorn.js:4627:15)
    at Parser.pp$8.nextToken (node_modules/acorn/dist/acorn.js:4618:15)
    at Parser.pp$8.next (node_modules/acorn/dist/acorn.js:4575:8)
    at Parser.pp.eat (node_modules/acorn/dist/acorn.js:577:10)
    at Parser.pp.semicolon (node_modules/acorn/dist/acorn.js:624:13)
    at Parser.pp$1.parseImport (node_modules/acorn/dist/acorn.js:1482:8)
    at Parser.pp$1.parseStatement (node_modules/acorn/dist/acorn.js:801:47)
    at Parser.parseStatement (node_modules/acorn-dynamic-import/lib/inject.js:47:31)
    at Parser.parseStatement (node_modules/acorn-import-meta/inject.js:39:50)
    at Parser.pp$1.parseTopLevel (node_modules/acorn/dist/acorn.js:706:23)
    at Parser.parse (node_modules/acorn/dist/acorn.js:551:15)
    at Object.parse (node_modules/acorn/dist/acorn.js:5287:37)
  pos: 972,
  loc: Position { line: 10, column: 0 },
  raisedAt: 972 }
    at node_modules/easygettext/src/extract-cli.js:71:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (node_modules/easygettext/src/extract-cli.js:57:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612
```

I have tried to add the ES7 plugin to acorn at `easygettext/src/extract.js:6` but it didn't make any difference or maybe I'm not doing it right?

- https://github.com/angelozerr/acorn-es7
- https://github.com/MatAtBread/acorn-es7-plugin

**Comment by vperron** [comment]
Hi does it still not work, @diego-vieira ?

**Comment by vperron** [comment]
Closing because: no news ;)

**Comment by diego-vieira** [comment]
@vperron sorry for my delay, I've just started working on this project again and the issue is still there.

```
node_modules/.bin/gettext-extract
gettext-extract --attribute v-translate --quiet --output /tmp/template.pot src/App.vue src/Dashboard.vue
[easygettext] extracting: 'src/App.vue
[easygettext] extracting: 'src/Dashboard.vue
[easygettext] could not read: 'src/Dashboard.vue
Trace: { SyntaxError: Unexpected character '@' (206:0)
    at Parser.pp$4.raise (/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp$8.getTokenFromCode (/node_modules/acorn/dist/acorn.js:4906:8)
    at Parser.<anonymous> (/node_modules/acorn-class-fields/inject.js:41:21)
    at Parser.getTokenFromCode (/node_modules/acorn-private-methods/inject.js:30:21)
    at Parser.pp$8.readToken (/node_modules/acorn/dist/acorn.js:4628:15)
    at Parser.pp$8.nextToken (/node_modules/acorn/dist/acorn.js:4619:15)
    at Parser.pp$8.next (/node_modules/acorn/dist/acorn.js:4576:8)
    at Parser.pp.eat (/node_modules/acorn/dist/acorn.js:577:10)
    at Parser.pp.semicolon (/node_modules/acorn/dist/acorn.js:624:13)
    at Parser.pp$1.parseImport (/node_modules/acorn/dist/acorn.js:1482:8)
    at Parser.pp$1.parseStatement (/node_modules/acorn/dist/acorn.js:801:47)
    at Parser.parseStatement (/node_modules/acorn-dynamic-import/lib/inject.js:47:31)
    at Parser.parseStatement (/node_modules/acorn-import-meta/inject.js:39:50)
    at Parser.pp$1.parseTopLevel (/node_modules/acorn/dist/acorn.js:706:23)
    at Parser.parse (/node_modules/acorn/dist/acorn.js:551:15)
    at Object.parse (/node_modules/acorn/dist/acorn.js:5288:37)
  pos: 960,
  loc: Position { line: 206, column: 0 },
  raisedAt: 960 }
    at /node_modules/easygettext/src/extract-cli.js:76:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/node_modules/easygettext/src/extract-cli.js:57:7)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
make: *** [/tmp/template.pot] Error 1
```

Basically we can't have es7 decorators.

```
@Component({
  components: {
    Header
  }
})
```

Thanks

**Comment by vperron** [comment]
OK :) 

Could you investigate ? Maybe bump acorn or make it resilient to "@" characters ? I really don't have the time to investigate but I'd like to read a pull request.

**Comment by diego-vieira** [comment]
Sure, leave that with me.

**Comment by vperron** [comment]
Thanks a million :) The upcoming weeks are hard to me.

**Comment by tcitworld** [comment]
I did have a look at this after #59 by upgrading acorn-es7 to the latest but I don't much about acorn so this may take a while : https://github.com/tcitworld/acorn-es7
