### ISSUE TITLE
Add an option to disable parsing JavaScript

### ISSUE THREAD

**Issue by junish** [Polyconseil/easygettext#55]
After pull request #53, `gettext-extract` doesn't work in TypeScript or with Flowtype.

Could you add an option to disable `extractor.parseJavascript` to avoid the problem?

This is a sample code to add the option:
https://github.com/junish/easygettext/commit/d55f67582060a4e894b490c0d583935d882e9914

Thank you.

**Comment by vperron** [comment]
Hello,

I'm not sure this is the best way to correct the issue; other options would include:
- detecting that the script is Flowtype-enabled or TypeScript and avoid the parsing
- only parse when we detect valid, non flowtype-enabled Javascript

But still if you make a PR with this code and the associated test, I'll be happy to merge it !

**Comment by vperron** [comment]
I would LOVE to see all of this added to the README as now supported features !

**Comment by vperron** [comment]
I think I'll make you a core contributor real soon :)

**Comment by junish** [comment]
I'm looking forward to new release. Thanks.

**Comment by vperron** [comment]
As soon as the documentation is updated, I'll gladly do it add you to the contributors so that you can merge the PRs and create new releases. (but please continue the pull requests !)

**Comment by vperron** [comment]
Will you make a PR for the docs please  ? 
![image](https://user-images.githubusercontent.com/88618/54027954-9f52f700-41a3-11e9-8750-896a174dc26a.png)

**Comment by wjdp** [comment]
@vperron @junish Is there any way of using easygettext with TypeScript? Just fired it up and it's tripping over any non-standard syntax:

```
[easygettext] could not read: 'js/views/GenericView.vue
Trace: { SyntaxError: Unexpected character '@' (6:0)
    at Parser.pp$4.raise (/home/will/local/scion/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp$8.getTokenFromCode (/home/will/local/scion/node_modules/acorn/dist/acorn.js:4906:8)
    at Parser.<anonymous> (/home/will/local/scion/node_modules/acorn-class-fields/inject.js:41:21)
    at Parser.getTokenFromCode (/home/will/local/scion/node_modules/acorn-private-methods/inject.js:30:21)
    at Parser.pp$8.readToken (/home/will/local/scion/node_modules/acorn/dist/acorn.js:4628:15)
    at Parser.pp$8.nextToken (/home/will/local/scion/node_modules/acorn/dist/acorn.js:4619:15)
    at Parser.pp$8.next (/home/will/local/scion/node_modules/acorn/dist/acorn.js:4576:8)
    at Parser.pp.eat (/home/will/local/scion/node_modules/acorn/dist/acorn.js:577:10)
    at Parser.pp.semicolon (/home/will/local/scion/node_modules/acorn/dist/acorn.js:624:13)
    at Parser.pp$1.parseImport (/home/will/local/scion/node_modules/acorn/dist/acorn.js:1482:8)
    at Parser.pp$1.parseStatement (/home/will/local/scion/node_modules/acorn/dist/acorn.js:801:47)
    at Parser.parseStatement (/home/will/local/scion/node_modules/acorn-dynamic-import/lib/inject.js:47:31)
    at Parser.parseStatement (/home/will/local/scion/node_modules/acorn-import-meta/inject.js:39:50)
    at Parser.pp$1.parseTopLevel (/home/will/local/scion/node_modules/acorn/dist/acorn.js:706:23)
    at Parser.parse (/home/will/local/scion/node_modules/acorn/dist/acorn.js:551:15)
    at Object.parse (/home/will/local/scion/node_modules/acorn/dist/acorn.js:5288:37) pos: 228, loc: Position { line: 6, column: 0 }, raisedAt: 228 }
    at /home/will/local/scion/node_modules/easygettext/src/extract-cli.js:76:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/will/local/scion/node_modules/easygettext/src/extract-cli.js:57:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by vperron** [comment]
Hi, could you investigate a bit more ? 

Did you correctly set "lang" to "ts"  ? We have tests about this, the Typescript code should be ignored.

**Comment by wjdp** [comment]
Apologies the above is caused by a decorator (issue #49) rather than typescript syntax.
